// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWGwiylG8RAPnUMv8hZ1mYSsMMwbfa-A',
    appId: '1:989674409097:web:4a631a5135e7df69390a58',
    messagingSenderId: '989674409097',
    projectId: 'ride-way-app',
    authDomain: 'ride-way-app.firebaseapp.com',
    storageBucket: 'ride-way-app.firebasestorage.app',
    measurementId: 'G-MYGDK7HMGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw1BqMRcg1capWb7pdyb25mU6X0sssAPU',
    appId: '1:989674409097:android:b4354de7342e0e75390a58',
    messagingSenderId: '989674409097',
    projectId: 'ride-way-app',
    storageBucket: 'ride-way-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEdHqk9olkxBMzxtkvILcZJn4nCvjvgvY',
    appId: '1:989674409097:ios:a06e0432d081ce94390a58',
    messagingSenderId: '989674409097',
    projectId: 'ride-way-app',
    storageBucket: 'ride-way-app.firebasestorage.app',
    iosClientId: '989674409097-lv8h2dnk8et0deftccvf095pbe3art5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEdHqk9olkxBMzxtkvILcZJn4nCvjvgvY',
    appId: '1:989674409097:ios:a06e0432d081ce94390a58',
    messagingSenderId: '989674409097',
    projectId: 'ride-way-app',
    storageBucket: 'ride-way-app.firebasestorage.app',
    iosClientId: '989674409097-lv8h2dnk8et0deftccvf095pbe3art5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWGwiylG8RAPnUMv8hZ1mYSsMMwbfa-A',
    appId: '1:989674409097:web:a91d120dc6c5e381390a58',
    messagingSenderId: '989674409097',
    projectId: 'ride-way-app',
    authDomain: 'ride-way-app.firebaseapp.com',
    storageBucket: 'ride-way-app.firebasestorage.app',
    measurementId: 'G-ZQ9VYKPSX2',
  );
}
